name: pyecca
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - matplotlib
  - numpy
  - scipy
  - control
  - pydot
  - autopep8
  - pytest=5.0.1
  - pyulog
  - pylint
  - jupyterlab
  - pip:
    - casadi
    - simpy
