name: pyecca
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - matplotlib
  - numpy
  - scipy
  - control
  - pydot
  - autopep8
  - pytest
  - pyulog
  - pylint
  - jupyterlab
  - sympy
  - pip:
    - casadi
    - simpy
